/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.pattern.java;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Map;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void itShouldBldMapWithRightValuesWhenMakeMapIsCalledWithStrs() {
        Map<String, String> mappedParams = new App().makeMapProperties("-Pname=cruz", "-Ptest=one");
        Assertions.assertEquals(mappedParams.getOrDefault("name", ""), "cruz");
        Assertions.assertEquals(mappedParams.getOrDefault("test", ""), "one");
    }
    @Test
    public void itShouldAvoidBadParamStructureWhenIsCalledWithStrs() {
        Map<String, String> mappedParams = App.makeMapProperties("name=cruz", "-test=one", "-Ptesttwo");
        Assertions.assertTrue(mappedParams.isEmpty());
    }
}
