/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.pattern.kotlin

fun makeMapProperties(vararg args: String?): Map<String, String> {
    return args
        .filterNotNull()
        .filter { arg -> arg.startsWith("-P")}
        .filter { arg -> arg.contains("=")}
        .fold(mutableMapOf()) { acc, validArg ->
            acc[validArg.split(Regex("="))[0].trim().split("-P")[1]] =
                validArg.split(Regex("=")
            )[1].trim()
            acc
        }
}

fun greeting(): String {
    return "Hello world"
}

fun main(args: Array<out String?>) {
    println(greeting())
    val params = makeMapProperties(*args)
    println(params.keys)
}